### PR TITLE
Replace Cake.Figlet with Spectre.Console

### PR DESCRIPTION
**Pull request by pascalberger**
Replace Cake.Figlet addin with Spectre.Console calls, which is already shipped as part of Cake

### CODE REVIEW

**Comment by pascalberger** [comment]
@gep13 Rebased and ready for review

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
Doh! I rebased it as well and force pushed it 😄

**Comment by gep13** [comment]
@pascalberger thanks for getting this fixed up!

**Pull request merged**
